//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public Nullable<double> EstimatePressure { get; set; }
        public Nullable<double> ActualPressure { get; set; }
        public Nullable<double> PressureDiff { get; set; }
    }
}
